Myte/Myte/Controllers/RegistroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Myte.Data;
using Myte.Models;

namespace Myte.Controllers
{
    [Authorize(Policy = "RequerFuncOuAdmin")]
    public class RegistroesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public RegistroesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult AdmIndex()
        {
            return View();
        }

        // GET: Registroes
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var funcionario = await _context.Funcionario.FirstOrDefaultAsync(f => f.Email == user.Email);

            if (funcionario == null)
            {
                return NotFound("Funcionário não encontrado.");
            }

            var registros = _context.Registro
                .Include(r => r.Funcionario)
                .Include(r => r.WBS)
                .Where(r => r.FuncionarioId == funcionario.FuncionarioId);

            return View(await registros.ToListAsync());
        }

        // GET: Registroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro
                .Include(r => r.Funcionario)
                .Include(r => r.WBS)
                .FirstOrDefaultAsync(m => m.RegistroId == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }

        // GET: Registroes/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var funcionario = await _context.Funcionario.FirstOrDefaultAsync(f => f.Email == user.Email);

            if (funcionario == null)
            {
                return NotFound("Funcionário não encontrado.");
            }

            ViewData["WBSId"] = new SelectList(_context.WBS, "WBSId", "Codigo");
            return View(new Registro { FuncionarioId = funcionario.FuncionarioId });
        }

        // POST: Registroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RegistroId,WBSId,HorasTrab,DataRegistro")] Registro registro)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var funcionario = await _context.Funcionario.FirstOrDefaultAsync(f => f.Email == user.Email);

                if (funcionario == null)
                {
                    return NotFound("Funcionário não encontrado.");
                }

                registro.FuncionarioId = funcionario.FuncionarioId;
                _context.Add(registro);
                await _context.SaveChangesAsync();
                TempData["message"] = "REGISTRO CADASTRADO COM SUCESSO";
                return RedirectToAction(nameof(Index));
            }

            ViewData["WBSId"] = new SelectList(_context.WBS, "WBSId", "Codigo", registro.WBSId);
            return View(registro);
        }

        // GET: Registroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro.FindAsync(id);
            if (registro == null)
            {
                return NotFound();
            }
            ViewData["FuncionarioId"] = new SelectList(_context.Set<Funcionario>(), "FuncionarioId", "FuncionarioNome", registro.FuncionarioId);
            var wbsList = _context.WBS.Select(w => new { w.WBSId, w.Codigo }).ToList();
            ViewData["WBSId"] = new SelectList(wbsList, "WBSId", "Codigo", registro.WBSId);
            return View(registro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RegistroId,FuncionarioId,WBSId,HorasTrab,DataRegistro")] Registro registro)
        {
            if (id != registro.RegistroId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registro);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "REGISTRO EDITADO COM SUCESSO";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroExiste(registro.RegistroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FuncionarioId"] = new SelectList(_context.Set<Funcionario>(), "FuncionarioId", "FuncionarioNome", registro.FuncionarioId);
            var wbsList = _context.WBS.Select(w => new { w.WBSId, w.Codigo }).ToList();
            ViewData["WBSId"] = new SelectList(wbsList, "WBSId", "Codigo", registro.WBSId);
            return View(registro);
        }

        [Authorize(Roles = "Admin")]
        // GET: Registroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro
                .Include(r => r.Funcionario)
                .Include(r => r.WBS)
                .FirstOrDefaultAsync(m => m.RegistroId == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }

        [Authorize(Roles = "Admin")]
        // POST: Registroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registro = await _context.Registro.FindAsync(id);
            if (registro != null)
            {
                _context.Registro.Remove(registro);
            }

            await _context.SaveChangesAsync();
            TempData["message"] = "REGISTRO DELETADO COM SUCESSO";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ObterOpcoesWBS()
        {
            var opcoesWBS = await _context.WBS.Select(w => new { w.WBSId, w.Codigo, w.Tipos, w.Descricao }).ToListAsync();


            return Json(opcoesWBS);
        }

        [HttpPost]
        public async Task<IActionResult> SalvarDados([FromBody] List<Registro> registros)
        {
            if (registros == null || !registros.Any())
            {
                Console.WriteLine("Nenhum dado recebido.");
                return BadRequest("No data received");
            }

            foreach (var registro in registros)
            {
                Console.WriteLine($"Recebido: FuncionarioId = {registro.FuncionarioId}, WBSId = {registro.WBSId}, HorasTrab = {registro.HorasTrab}, DataRegistro = {registro.DataRegistro}");
                _context.Registro.Add(registro);
            }
            await _context.SaveChangesAsync();
            TempData["message"] = "REGISTRO CADASTRADO COM SUCESSO";
            return Ok();
        }

        private bool RegistroExiste(int id)
        {
            return _context.Registro.Any(e => e.RegistroId == id);
        }
    }
}

Myte/Myte/Views/Registroes/Create.cshtml
@model Myte.Models.Registro

@{
    ViewData["Title"] = "Registrar Horas";
}
@if (TempData["message"] != null)
{
    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}

<style>
    .background-image {
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        width: 100%;
        height: 100%;
        object-fit: cover;
        opacity: 0.5;
    }

    .texto-centro-btn {
        display: flex;
        justify-content: center;
        margin-top: 10px;
    }

    .tabela-wbs {
        background-image: url('~/IMG/IMG3.png');
        background-size: cover;
        background-position: center;
        background-color: white;
    }

    .disabled-input {
        background-color: #f8f9fa;
    }

    #tabelaHorasTrabalho thead th {
        background-color: white;
        color: black;
    }

    #tabelaHorasTrabalho tbody td, #tabelaHorasTrabalho tbody th {
        text-align: center;
    }

    .title-style {
        color: black;
        font-size: 45px;
        font-weight: bold;
        text-shadow: 2px 2px 4px rgba(255, 255, 255, 0.8);
    }

    .total-horas {
        background-color: white;
    }

</style>

<img src="~/IMG/IMG3.png" class="background-image" alt="Background Image">

<div style="text-align: center;">
    <h1 class="title-style">Registro de Horas</h1>
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <div class="card">          
                <div class="card-body">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="DataRegistro" class="control-label"><strong>Data Registro:</strong></label>
                            <input type="date" class="form-control" id="dataInicio" />
                            <span asp-validation-for="DataRegistro" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="DataRegistro" class="control-label"><strong>Data Final:</strong></label>
                            <input type="date" class="form-control" id="dataFim" />
                            <span asp-validation-for="DataRegistro" class="text-danger"></span>
                        </div>
                        <br />
                        <th colspan="2">
                            <div class=" text-center">
                                <button type="button" class="btn btn-dark" onclick="gerarTabela()">Gerar Tabela</button>
                            </div>
                        </th>

                        <div class="form-group">
                            <input type="hidden" id="FuncionarioId" value="@Model.FuncionarioId" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-3">
    <table class="table table-bordered tabela-wbs" id="tabelaHorasTrabalho">
        <thead>
            <tr>
            </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
        </tfoot>
    </table>
</div>

<div class="container mt-3 text-center">
    <button class="btn btn-success mb-3" id="botaoEnviar" onclick="enviarDados()">Enviar</button>
    <a asp-action="Index" class="btn btn-secondary mb-3">Voltar</a>
</div>

@section Scripts {
    <script>
        const arrayDadosEnviados = [];
        let opcoesWBS = '';

        function carregarOpcoesWBS(callback) {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("ObterOpcoesWBS", "Registroes")',
                success: function (dados) {
                    opcoesWBS = '<option value="">Selecionar</option>';
                    dados.forEach(wbs => {
                            opcoesWBS += `<option value="${wbs.wbsId}">${wbs.codigo} - ${wbs.descricao}</option>`;
                    });
                    if (callback) callback();
                },
                error: function (erro) {
                    console.error('Erro ao carregar opções de WBS', erro);
                }
            });
        }

        function gerarTabela() {
            $('#tabelaHorasTrabalho thead tr').empty();
            $('#tabelaHorasTrabalho tbody').empty();
            $('#tabelaHorasTrabalho tfoot').empty();

            $('#tabelaHorasTrabalho thead tr').append('<th>WBS</th>');

            const dataInicio = new Date($('#dataInicio').val());
            const dataFim = new Date($('#dataFim').val());

            const datas = [];
            let dataAtual = dataInicio;
            while (dataAtual <= dataFim) {
                datas.push(new Date(dataAtual));
                dataAtual.setDate(dataAtual.getDate() + 1);
            }

            datas.forEach(data => {
                const dataStr = data.toISOString().split('T')[0];
                $('#tabelaHorasTrabalho thead tr').append(`<th>${dataStr}</th>`);
            });

            for (let i = 0; i < 5; i++) {
                let linha = `<tr><td><select class="form-control tarefa-select">${opcoesWBS}</select></td>`;
                datas.forEach(data => {
                    const dia = data.getDay();
                    const fimDeSemana = (dia === 5 || dia === 6);
                    const campoEntrada = `<td><input type="number" class="form-control horas-input${fimDeSemana ? ' disabled-input' : ''}"
                                                                                                                            ${fimDeSemana ? 'disabled' : ''}
                                                                                                                            min="0" max="24"
                                                                                                                            data-date="${data.toISOString().split('T')[0]}"
                                                                                                                            onchange="atualizarTotais('${data.toISOString().split('T')[0]}')">
                                                                                                                    </td>`;
                    linha += campoEntrada;
                });
                linha += '</tr>';
                $('#tabelaHorasTrabalho tbody').append(linha);
            }

            let linhaTotal = '<tr class="total-horas"><td><strong>TOTAL DE HORAS:</strong></td>';
            datas.forEach(data => {
                const dataStr = data.toISOString().split('T')[0];
                linhaTotal += `<td id="total-${dataStr}">0</td>`;
            });
            linhaTotal += '</tr>';
            $('#tabelaHorasTrabalho tbody').append(linhaTotal);
        }

        function enviarDados() {
            if ($('#botaoEnviar').prop('disabled')) {
                alert("Não é permitido lançar mais de 12 horas por dia.");
                return;
            }

            const funcionarioId = $('#FuncionarioId').val();
            const dadosTabela = [];
            const datas = [];
            $('#tabelaHorasTrabalho thead th').each(function (index) {
                if (index > 0) datas.push($(this).text());
            });

            $('#tabelaHorasTrabalho tbody tr').each(function () {
                const linha = $(this);
                const wbs = linha.find('select').val();
                if (wbs === undefined || wbs === "") {
                    console.error("WBS não selecionado para uma das linhas.");
                    return;
                }
                linha.find('input[type="number"]').each(function (index) {
                    const horas = $(this).val();
                    if (horas) {
                        const data = datas[index];
                        dadosTabela.push({ FuncionarioId: funcionarioId, WBSId: wbs, HorasTrab: horas, DataRegistro: data });
                    }
                });
            });

            $.ajax({
                type: 'POST',
                url: '@Url.Action("SalvarDados", "Registroes")',
                data: JSON.stringify(dadosTabela),
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    window.location.href = '@Url.Action("Index", "Registroes")';
                },
                error: function (xhr, status, error) {
                    console.error('Erro ao enviar dados:', status, error);
                    console.error('Resposta do servidor:', xhr.responseText);
                }
            });
        }

        function atualizarTotais(data) {
            let totalHoras = 0;
            $(`input[data-date="${data}"]`).each(function () {
                totalHoras += parseFloat($(this).val()) || 0;
            });

            $(`#total-${data}`).text(totalHoras);

            if (totalHoras > 12) {
                $(`input[data-date="${data}"]`).each(function () {
                    $(this).addClass('is-invalid');
                });
                alert("Não é permitido lançar mais de 12 horas por dia.");
                $('#botaoRegistrar').prop('disabled', true);
                $('#botaoEnviar').prop('disabled', true);
            } else {
                $(`input[data-date="${data}"]`).each(function () {
                    $(this).removeClass('is-invalid');
                });
                $('#botaoRegistrar').prop('disabled', false);
                $('#botaoEnviar').prop('disabled', false);
            }

            let totalTrabalhadas = 0;
            $(`#tabelaHorasTrabalho tbody tr`).not(':last').find(`input[data-date="${data}"]`).each(function () {
                totalTrabalhadas += parseFloat($(this).val()) || 0;
            });
            $(`#total-${data}`).text(totalTrabalhadas);
        }

        $(document).ready(function () {
            carregarOpcoesWBS();
        });
    </script>
}

Myte/Myte/Views/Registroes/Delete.cshtml
@model Myte.Models.Registro

@{
    ViewData["Title"] = "Apagar Registro";
}

@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}

<style>
    .background-image {
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        width: 100%;
        height: 100%;
        object-fit: cover;
        opacity: 0.6;
    }

    .text-center-btn {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }

    .white-background {
        background-color: white;
    }
</style>

<img src="~/IMG/IMG3.png" class="background-image" alt="Background Image">

<div class="container mt-6">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">DELETAR REGISTRO</h2>
                    <hr />
                    <div class="card white-background">
                        <div class="card-body">
                            <dl class="row">
                                <dt class="col-sm-5">
                                    @Html.DisplayNameFor(model => model.Funcionario)
                                </dt>
                                <dd class="col-sm-5">
                                    @Html.DisplayFor(model => model.Funcionario.FuncionarioNome)
                                </dd>
                                <hr />

                                <dt class="col-sm-5">
                                    @Html.DisplayNameFor(model => model.WBS)
                                </dt>
                                <dd class="col-sm-5">
                                    @Html.DisplayFor(model => model.WBS.Codigo)
                                </dd>
                                <hr />
                                <dt class="col-sm-5">
                                    @Html.DisplayNameFor(model => model.HorasTrab)
                                </dt>
                                <dd class="col-sm-5">
                                    @Html.DisplayFor(model => model.HorasTrab)
                                </dd>
                                <hr />
                                <dt class="col-sm-5">
                                    @Html.DisplayNameFor(model => model.DataRegistro)
                                </dt>
                                <dd class="col-sm-5">
                                    @Html.DisplayFor(model => model.DataRegistro)
                                </dd>
                                <hr />
                            </dl>
                        </div>
                    </div>

                    <div class="text-center-btn">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="RegistroId" />
                            <input type="submit" value="Deletar" class="btn btn-danger" /> |
                            <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Myte/Myte/Views/Registroes/Details.cshtml
@model Myte.Models.Registro

@{
    ViewData["Title"] = "Detalhes Registro";
}

@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}

<style>
    .background-image {
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        width: 100%;
        height: 100%;
        object-fit: cover;
        opacity: 0.6;
    }

    .text-center-content {
        text-align: center;
    }

    .text-center-btn {
        text-align: center;
        margin-top: 20px;
    }
</style>

<img src="~/IMG/IMG3.png" class="background-image" alt="Background Image">

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">DETALHES DO REGISTRO</h2>                    
                    <dl class="row">
                        <dt class="col-sm-5">
                            @Html.DisplayNameFor(model => model.Funcionario)
                        </dt>
                        <dd class="col-sm-5">
                            @Html.DisplayFor(model => model.Funcionario.FuncionarioNome)
                        </dd>
                        <dt class="col-sm-5">
                            @Html.DisplayNameFor(model => model.WBS)
                        </dt>
                        <dd class="col-sm-5">
                            @Html.DisplayFor(model => model.WBS.Codigo)
                        </dd>
                        <dt class="col-sm-5">
                            @Html.DisplayNameFor(model => model.HorasTrab)
                        </dt>
                        <dd class="col-sm-5">
                            @Html.DisplayFor(model => model.HorasTrab)
                        </dd>
                        <dt class="col-sm-5">
                            @Html.DisplayNameFor(model => model.DataRegistro)
                        </dt>
                        <dd class="col-sm-5">
                            @Html.DisplayFor(model => model.DataRegistro)
                        </dd>
                    </dl>
                </div>
                <div class="form-group text-center">
                    <a asp-action="Edit" asp-route-id="@Model?.RegistroId" class="btn btn-dark">Editar</a> |
                    <a asp-action="Index" class="btn btn-secondary ml-3">Voltar</a>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

Myte/Myte/Views/Registroes/Edit.cshtml
@model Myte.Models.Registro

@{
    ViewData["Title"] = "Editar Registro";
}

@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}

<style>
    .background-image {
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        width: 100%;
        height: 100%;
        object-fit: cover;
        opacity: 0.6;
    }

    .form-container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }

    .gray-button {
        background-color: gray;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        margin-right: 10px;
    }
</style>

<img src="~/IMG/IMG3.png" class="background-image" alt="Background Image">

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">EDITAR REGISTRO</h2>
                    <hr />
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-5">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="RegistroId" />
                                <br />
                                <div class="form-group">
                                    <label asp-for="FuncionarioId" class="control-label"><strong>ID Funcionário:</strong></label>
                                    <select asp-for="FuncionarioId" class="form-control" asp-items="ViewBag.FuncionarioId"></select>
                                    <span asp-validation-for="FuncionarioId" class="text-danger"></span>
                                </div>
                                <br />
                                <div class="form-group">
                                    <label asp-for="WBSId" class="control-label"><strong>Código WBS:</strong></label>
                                    <select asp-for="WBSId" class="form-control" asp-items="ViewBag.WBSId"></select>
                                    <span asp-validation-for="WBSId" class="text-danger"></span>
                                </div>
                                <br />
                                <div class="form-group">
                                    <label asp-for="HorasTrab" class="control-label"><strong>Horas Trabalhadas:</strong></label>
                                    <input asp-for="HorasTrab" class="form-control" />
                                    <span asp-validation-for="HorasTrab" class="text-danger"></span>
                                </div>
                                <br />
                                <div class="form-group">
                                    <label asp-for="DataRegistro" class="control-label"><strong>Data Registro:</strong></label>
                                    <input asp-for="DataRegistro" class="form-control" />
                                    <span asp-validation-for="DataRegistro" class="text-danger"></span>
                                </div>
                                <br />
                                <div class="form-group text-center">
                                    <input type="submit" value="Salvar" class="btn btn-dark" /> |
                                    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                                </div>
                                <br />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}